baseURL = "https://eriritarded.github.io/"
title = "AIKATSU"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386.fork"
preserveTaxonomyNames = true
relativeurls = true
canonifyURLs = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "AIKATSU.MOE"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Now the trouble about trying to make yourself stupider than you really are is that you very often succeed." 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = ""

    # The name to display in the copyright section in the footer
    copyrightname = "Hoshimiya Ichigo"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false
	
	# set theme to full screen width
	fullWidthTheme = true

    # Urls for social networks
    facebook = "https://anilist.co/user/aikatsu/"
    twitter = "https://rateyourmusic.com/~aikatsu"
    linkedin = "https://www.last.fm/user/eriritarded"
    github = "https://letterboxd.com/aikatsu/"
    gitlab = "https://glitchwave.com/user/aikatsu/"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "HOSHIMIYA"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = "Commence Idol Activities"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"       # The path can lead to a content folder too.
    weight = 20
	
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 30
	
  [[menu.main]]
    identifier = "lapana"
    name = "Lapana"
    url = "/lapana/"       # The path can lead to a content folder too.
    weight = 40
	
[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
